name: 50 DAST Scan Docker Image

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

env:
  IMAGE_TAG: observatorio_backend:latest

jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_TAG }} .

      - name: Start demo app container
        run: |
          docker run -d -p 5006:5006 --name demoApp \
            -e COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} \
            -e COSMOS_KEY=${{ secrets.COSMOS_KEY }} \
            ${{ env.IMAGE_TAG }}

      - name: Check container status
        run: docker ps

      - name: Inspect container logs
        run: docker logs demoApp

      - name: Test container endpoint
        run: |
          echo "Verificando si el servicio responde en localhost:5006..."
          for i in {1..10}; do
            if curl -s http://localhost:5006 > /dev/null; then
              echo "El servicio está disponible."; exit 0;
            fi
            echo "Intento $i: El servicio no está disponible, reintentando...";
            sleep 5;
          done
          echo "El servicio no pudo inicializarse."; exit 1

      - name: Pull and Run ZAP
        run: |
          docker pull owasp/zap2docker-live
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-live zap-full-scan.py -t http://localhost:5006 -r zap_report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP_Report
          path: zap_report.html

      - name: Stop and clean up Docker container
        if: always()
        run: |
          docker stop demoApp && docker rm demoApp
          docker container prune --force
          docker image prune --force
