name: DAST Scan

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

env:
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} .

      - name: Start demo app container
        run: |
          docker rm -f demoApp || true
          docker run -d -p 3006:3006 --name demoApp \
            -e AZURE_COSMOS_DB_URL=${{ secrets.AZURE_COSMOS_DB_URL }} \
            -e AZURE_COSMOS_DB_KEY=${{ secrets.AZURE_COSMOS_DB_KEY }} \
            ${{ env.IMAGE_TAG }}

      - name: Inspect container logs
        run: docker logs demoApp

      - name: Wait for container to start
        run: |
          echo "Esperando que el contenedor esté disponible en localhost:3006..."
          for i in {1..20}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3006 || echo "000")
            echo "HTTP status: $status"
            if [ "$status" == "200" ]; then
              echo "El servicio está disponible."
              exit 0
            fi
            echo "El servicio aún no está disponible, reintentando..."
            sleep 5
          done
          echo "El servicio no se pudo iniciar."
          docker logs demoApp
          exit 1

      - name: Test container endpoint
        run: curl -i http://localhost:3006

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3006'
          cmd_options: '-a -j -l WARN -z "-addoninstallall"'
          allow_issue_writing: false

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: DAST_Report.html
          path: report_html.html

      - name: Stop and clean up Docker container
        if: always()
        run: |
          docker stop demoApp && docker rm demoApp
          docker container prune --force
          docker image prune --force
