name: 50 DAST Scan Docker Image

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

env:
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Construyendo la imagen Docker..."
          docker build -t ${{ env.IMAGE_TAG }} .

      - name: Start demo app container
        run: |
          echo "Iniciando el contenedor de la aplicación..."
          docker rm -f demoApp || true
          docker run -d -p 3006:3006 --name demoApp ${{ env.IMAGE_TAG }}

      - name: Inspect container logs
        run: |
          echo "Inspeccionando los logs del contenedor..."
          docker logs demoApp

      - name: Wait for container to start
        run: |
          echo "Esperando que el contenedor esté disponible en localhost:3006..."
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w '%{http_code}' localhost:3006 || echo "000")
            echo "Intento $i: HTTP status: $STATUS"
            if [ "$STATUS" == "200" ]; then
              echo "El servicio está disponible."
              exit 0
            fi
            echo "Logs del contenedor:"
            docker logs demoApp
            echo "El servicio aún no está disponible, reintentando..."
            sleep 10
          done
          echo "Error: El servicio no inició correctamente."
          docker logs demoApp
          exit 1

      - name: Test container endpoint
        run: |
          echo "Probando el endpoint de la aplicación..."
          curl -i http://localhost:3006

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3006'
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: '-a -j -l WARN -z "-addoninstallall"'
          allow_issue_writing: false

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: DAST_Report.html
          path: report_html.html

      - name: Stop and clean up Docker container
        if: always()
        run: |
          echo "Deteniendo y eliminando el contenedor Docker..."
          docker stop demoApp && docker rm demoApp
          docker container prune --force
          docker image prune --force
