name: 05 DAST

on:
  workflow_call:
    inputs:
      target:
        type: string
        description: 'The target URL for DAST scan'
        required: true

jobs:
  zap_scan:
    name: Scan the Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ inputs.target }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
