name: 05 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Instalar license-checker
      - name: Install License Checker
        run: npm install -g license-checker

      # Ejecutar análisis de licencias
      - name: Run License Compliance Check
        id: license-check
        run: |
          license-checker --production --json > license_report.json
          echo "License compliance check completed"

      # Validar contra licencias permitidas
      - name: Validate Licenses
        run: |
          node -e "
          const fs = require('fs');
          const permittedLicenses = ['MIT', 'Apache-2.0'];
          const report = JSON.parse(fs.readFileSync('license_report.json', 'utf-8'));
          const invalid = Object.entries(report).filter(([pkg, data]) => !permittedLicenses.includes(data.licenses));
          if (invalid.length) {
            console.error('Found invalid licenses:');
            invalid.forEach(([pkg, data]) => console.error(\`\${pkg}: \${data.licenses}\`));
            process.exit(1);
          } else {
            console.log('All licenses are compliant.');
          }"

      # Subir reporte de licencias como artefacto
      - name: Upload License Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: license-compliance-report
          path: license_report.json
